Repository WesleyKlop/IIPSEN, pull requests merged in 2018-06, with the labels that each got.

#37 End screen cldd
  src/main/java/client/ui/controllers/LayoutEndScreen.java
  src/main/resources/images/globetrotter.jpg
  src/main/resources/views/layout_end_screen.fxml
  src/main/resources/views/overlay_not_players_turn_message.fxml
  src/test/java/game/cards/CardStackTest.java
Labels: UI, enhancement

#36 Double route
  src/main/java/client/ui/factories/RouteViewFactory.java
  src/main/java/client/ui/game/GameCostsController.java
  src/main/java/game/actions/BuildRouteAction.java
  src/main/java/game/routecards/Route.java
  src/main/java/game/routecards/RouteDoubleCheck.java
  src/main/java/game/routecards/RouteStore.java
  src/main/resources/string/gameRoutes.xml
  src/test/java/game/routecards/RouteTest.java
Labels: enhancement, logic

#38 Feature/load game
  .gitignore
  src/main/java/client/Client.java
  src/main/java/client/GameClient.java
  src/main/java/client/GameStoreClient.java
  src/main/java/client/ui/controllers/LayoutEndScreen.java
  src/main/java/client/ui/controllers/RouteCardController.java
  src/main/java/client/ui/dialogs/MessagesController.java
  src/main/java/client/ui/game/GameCostsController.java
  src/main/java/client/ui/game/GameRoutesMapController.java
  src/main/java/client/ui/game/PauseMenuController.java
  src/main/java/client/ui/mainmenu/MainMenuLoadController.java
  src/main/java/client/ui/mainmenu/PreferencesController.java
  src/main/java/client/ui/mainmenu/StartupController.java
  src/main/java/client/ui/views/LayoutGamePlayerbox.java
  src/main/java/client/ui/views/LobbyController.java
  src/main/java/client/util/GameSaver.java
  src/main/java/game/GameStore.java
  src/main/java/game/GameStoreProvider.java
  src/main/java/game/actions/AddPlayerAction.java
  src/main/java/game/actions/AttachPlayerAction.java
  src/main/java/game/actions/BuildRouteAction.java
  src/main/java/game/actions/GetCardAction.java
  src/main/java/game/actions/SelectRouteCardsAction.java
  src/main/java/game/player/Player.java
  src/main/java/game/player/PlayerController.java
  src/main/java/game/routecards/Route.java
  src/main/java/server/Server.java
  src/main/resources/views/layout_main_menu_load.fxml
  src/main/resources/views/layout_save_menu.fxml
  src/main/resources/views/overlay_pause_menu.fxml
  src/test/java/game/GameStoreTest.java
  src/test/java/game/actions/AddPlayerActionTest.java
  src/test/java/game/actions/BuildRouteActionTest.java
  src/test/java/game/actions/ChangeStateActionTest.java
  src/test/java/game/actions/SelectRouteCardsActionTest.java
Labels: UI, enhancement, logic
